default:
  desc: 帮助文件
  cmds:
    - task -l

deps:
  desc: 下载依赖包
  dir: src/vendor
  cmds:
    - which gopm || go get -u github.com/gpmgo/gopm
    - ../../scripts/deps.sh

build:
  desc: 编译应用
  cmds:
    - GOPATH=`pwd` GOBIN=`pwd` go install src/p/cmd/main.go

dev:
  desc: 编译应用
  cmds:
    - ./main --home test/d node

build_linux:
  desc: 交叉编译成linux应用
  cmds:
    - GOPATH=`pwd` GOBIN=`pwd` CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install src/p/cmd/main.go

docker_build:
  desc: 构建docker镜像
  cmds:
      - task: build_linux
      - docker build -t srelay .
      - docker tag srelay registry.yuanbenlian.com/yuanben/srelay

docker_push:
  desc: docker push
  cmds:
      - docker push registry.yuanbenlian.com/yuanben/srelay

docker_test:
  desc: kchain docker test
  cmds:
    - ls * | grep example_data || mkdir example_data
    - docker run --rm -it -v `pwd`/example_data:/kdata -p 46656:46656 -p 46657:46657 kchain init
    - docker run --rm -it -v `pwd`/example_data:/kdata -p 46656:46656 -p 46657:46657 kchain
    - rm -rf example_data
